### PR TITLE
Update AboutUs.md

### PR DESCRIPTION
**Pull request by jamessinmaojun**

### CODE REVIEW

**Review by chiageng — APPROVED** [review]
LGTM

**Review by Joshy837 — APPROVED** [review]
LGTM

**Comment by Joshy837** [comment]
@chiageng ready to merge

**Comment by chiageng** [comment]
@jamessinmaojun @Joshy837 @jannaleong @yleeyilin 
There is an update in team repo. Please pull latest commit into your local repo.

**Pull request merged**
