### PR TITLE
Update DeveloperGuide.md

### PR DESCRIPTION
**Pull request by jamessinmaojun**
Update glossary

### CODE REVIEW

**Comment by jamessinmaojun** [comment]
@jannaleong @Joshy837 I have updated the glossary please review tysm!

**Review by Joshy837 — APPROVED** [review]
Looks Good to me!

**Review by jannaleong — APPROVED** [review]
LGTM

**Comment by chiageng** [comment]
@jamessinmaojun @jannaleong @Joshy837 @yleeyilin 
There is an update in team repo, please pull into your local fork

**Pull request merged**
